### ISSUE TITLE
运行生成报错

### ISSUE THREAD

**Issue by magiboys** [util-core/Util.Generator#8]
sql server如果没建Demo.Generator数据库，运行报错 无法打开登录所请求的数据库 "Demo.Generator"。sa 登录失败,但是密码是对的，
如果新建了Demo.Generator空数据库，运行提示生成成功，但是输出目录没有任务代码生成

**Comment by UtilCore** [comment]
util代码生成器是基于数据库元数据生成代码的,所以你必须先创建Demo.Generator数据库,并创建相关的表,再生成代码
